### ISSUE TITLE
How to remove the right property for loadgo-overlay

### ISSUE THREAD

**Issue by andrewlim7** [franverona/loadgo#13]
My image is on the left side, but the loadgo appears on the right hand side. I realised this is caused by the right property = 0px; I think there is a bug for left to right direction. I tried using both jquery and no jquery and both are not working as well.

**Comment by franverona** [comment]
Hi @andrewlim7,

Sorry for the big delay in answering you. Is this error also ocurring using different directions? (right to left, or bottom to top for example)

**Comment by andrewlim7** [comment]
Hi franverona,

Its okay. I solved it by applying the properties from this class .loadgo-container{ margin: 0 auto; float: left; } then it works as expected. Thank you for the library! :)


On 16 Apr 2018, at 10:31 PM, Fran Verona <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @andrewlim7<https://github.com/andrewlim7>,

Sorry for the big delay in answering you. Is this error also ocurring using different directions? (right to left, or bottom to top for example)
