### ISSUE TITLE
Trying to get basic example working on website load and nothing happens

### ISSUE THREAD

**Issue by forwardtrends** [franverona/loadgo#5]
I have this in the head of my pages: 

```
<script src="<?php bloginfo('template_directory'); ?>/loadgo-master/loadgo.min.js" type="text/javascript"></script>
<script>
$(window).load(function () {
	$("#loaderlogo").load(function() {
	  $('#loaderlogo').loadgo();
	}).each(function() {
	  if(this.complete) $(this).load();
	});
});
</script>
```

With the loaderlogo image (inside a div) as the first html element after the body. Running jquery 2.2.3 (always updated to latest versions) - all I see is a logo at the top of the page, not centered, no overlay on page, and never begins loading. Is it a jquery version issue? Not getting any errors. Testing in Firefox.

**Comment by franverona** [comment]
Hi forwardtrends,

As I said in the documentation:

> This plugin won't control asynchronous behaviour for your loading process, so you have to do that by yourself in your app.

LoadGo is a visual plugin which provides some functions to simulate a loading process, but all this process (for example, increase uploading bar when page is loading) is not done by LoadGo. Thus, you should use LoadGo functions such as *setprogress* to update LoadGo loading status.

Furthermore, can you paste your HTML view? Not all of it, just the part or your **loaderlogo** div and its parent.

- Fran

**Comment by forwardtrends** [comment]
Thanks - I guess I misunderstood that sorry. Here's what the loader container and image code looks like: 

`<div><img src="<?php bloginfo('template_directory'); ?>/img/logo.png" id="loaderlogo" alt="Loading" /></div>`

I have an extensive jquery functions file written for other custom functionality, I assume I'd have to build the loading progress in there then.

**Comment by franverona** [comment]
Your HTML seems ok. Maybe your own CSS style is conflicting with some of LoadGo styles. If you also want the logo centered on page or more customized style, you have to create your own CSS styles and apply it to your logo.

I'm currently trying to create a version for Wordpress which uses [PACE](http://github.hubspot.com/pace/) to achieve an automatic "Loading page" process, but it's not as simple as I thought. I hope I can find a solution!

-Fran

**Comment by forwardtrends** [comment]
Thanks for your help! I'm already trying to integrate PACE for the loading just need to figure out both and write the functions. If you want I'll share my solution once I figure it out - I'm building it into one my my custom WordPress themes so it may be useful.

**Comment by franverona** [comment]
Would be fantastic! I'm currently digging into [WP Pace](https://es.wordpress.org/plugins/wp-pace/) source code to know how it works, but code is really old.

A lot of people are interest in a fully integrated WP solution (even me for my own page :laughing: ). It's a new world for me and I'm really excited to code a solution for Wordpress.

So feel free to share your knowledge if you want. Any help will be really appreciated :+1: 

-Fran

**Comment by forwardtrends** [comment]
No problem I'll share if and when I get it all sorted out - thanks again!

**Comment by franverona** [comment]
@forwardtrends 

By using PACE for Wordpress I found a very cool solution to use Loadgo with WP.

You can see a demo here: http://franverona.com/wordpress/

I also uploaded it to Youtube: https://youtu.be/VjSE7KzZU60

I setup my Chrome Dev tools to simulate a 2Mb/s connection and add some useless scripts to increase webpage size, so Loadgo effect can be seen.

I expect to release a version in a few weeks after do more tests, so I will contact you again (if you like) in a couple of weeks if you are still interested on integrating Loadgo with your WP website.

-Fran

**Comment by franverona** [comment]
@forwardtrends 

**LoadGo for WP** is alive (yay!)

I'm still waiting for Wordpress to accept my plugin submission, but in the meantime, your can download it from here:
[https://github.com/franverona/LoadGo-for-WP](https://github.com/franverona/LoadGo-for-WP)

**Comment by forwardtrends** [comment]
Thank you! I just tested the install and got an error: 

`Parse error: syntax error, unexpected '[' in ....../wp-content/plugins/LoadGo-for-WP-master/loadgo-options.php on line 385`

**Comment by franverona** [comment]
I'm unable to reproduce your error. I did a fresh installation of Wordpress (v4.5.1), then LoadGo and all seems to work fine.

What version of Wordpress and PHP are you using?

PS: can you open the issue in the repository, please? (https://github.com/franverona/LoadGo-for-WP)[https://github.com/franverona/LoadGo-for-WP]
