### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by franverona** [franverona/loadgo#6]
sazap10 did a great job by doing it here: https://github.com/sazap10/bower-loadgo

But according to [this discussion](https://github.com/sazap10/bower-loadgo/issues/1), maybe split bower package in two different packages (bower-loadgo and bower-nonjquery-loadgo, or similar) would be optimal in case that someone doesn't need jQuery in his project.

So I will mark this as a ToDo (I have to had a bower.json file to this repo as well). Feel free to ask any questions or thoughts you have.

-Fran

**Comment by ph168** [comment]
Could you find a solution to this yet?
Specifically, I wonder how to do the splitting as there can only be a single bower.json file in a repository.

Right now, I can think of two different approaches:

1. Moving the non-jquery version to a new repository and creating bower.json files in both the existing and the new repository.
2. Creating two “satellite” repositories for the two versions with a bower.json file each. Changes would need to be pushed to these repositories (could be automatized). The original repository would remain unchanged. (This was apparently also done in other projects)

What do you think?
