### ISSUE TITLE
Loadgo for load page

### ISSUE THREAD

**Issue by Dankof** [franverona/loadgo#9]
Hello,

Im just trying to use loadgo and pace to show the logo while the website is loading but can't make it work. Any suggestion?

PS: I'm not using wordpress, just an HTML file with all files necesaries.

Thank you

**Comment by franverona** [comment]
Hi Dankof,

Esentially you have to modify Pace.js script in order to combine it with LoadGo script. Please see this issue for an overview of a similar problem: https://github.com/franverona/loadgo/issues/8

Best regards,

-Fran

**Comment by Dankof** [comment]
I just copy the pace.js that you modified, and your modification from this: http://franverona.com/wploadgo/ 

About pace, do you think is enoguh or maybe change different things? Cause in your demo website, it works! :)

**Comment by franverona** [comment]
That demo site is entirely done using Wordpress, so I was assuming a couple of things about how Wordpress works. In your case, I think that you need to do "almost" the same, but with some things in mind first:

1. Inside Pace script, I update my logo overlay using LoadGo `setprogress` function, but my image is used as a variable called LOADGO_LOGO outside this script.

For example, [here](https://github.com/franverona/LoadGo-for-WP/blob/master/js/pace.js#L903) (line 903 of my custom Pace script):

```
// Loadgo modification
if (Loadgo && LOADGO_LOGO) {
  if (!isNaN(barProgress)) {
    Loadgo.setprogress(LOADGO_LOGO, barProgress);
    if (document.getElementById("loadgo-progress"))
      document.getElementById("loadgo-progress").innerHTML = parseInt(barProgress) + "%";
   }
}
```

I check if LoadGo global object exists (so that implies that LoadGo is actually loaded) and my logo also exists (LOADGO_LOGO is defined outside in my own script as `var LOADGO_LOGO = document.getElementById('loadgo-logo');`). After that, I check if barProgress has a numeric valid value, then I set the progress.

2. The LoadGo script must be loaded BEFORE Pace, so I can use it inside Pace to update my overlay progress. Wordpress allows me to load scripts based on priorities. In your case, you can do something like:

```
<script src="/loadgo/loadgo-nojquery.js"></script>
<script src="/pace/pace.js"></script>
```

LoadGo is also available as a pure JS version, so you don't need jQuery at all to use it.

Take a look at the [Wordpress plugin repository](https://github.com/franverona/LoadGo-for-WP) even if you don't know how Wordpress works. 

The [loadgo_sitewide.php](https://github.com/franverona/LoadGo-for-WP/blob/master/methods/loadgo_sitewide.php) file is used to add the HTML and JS with Pace and Loadgo. You will see that I add both scripts (LoadGo first, then Pace), and after that I create the HTML and a little inline JS code that I need to be executed as soon as possible. The trick was to create an interval that will be cleared as soon as LoadGo is loaded, then initiate LoadGo with my logo.

I hope it will help you, and let me know if you need more help.

-Fran

**Comment by Dankof** [comment]
The most strange is that the error that show me is: 
ReferenceError: Loadgo is not defined

Cause in the same page, it works with your demo logo, disney, etc.

Also follow your instructions to load loadgo before pace, and use a var for LOADGO_LOGO to call the elemet by ID.

I'm lost, can you give me a clue :) 

Thank you

**Comment by franverona** [comment]
Sure, no problem. Can you paste here how are you loading your JS scripts? You should load LoadGo, then Pace. And paste the code that you're using to create your "LoadGo" object (where you do something like `Loadgo.init(yourimage, yourparams)`).

-Fran

**Comment by Dankof** [comment]
Ok, im going to paste my whole html, I used the params of your wordpress demo, also created the same id to get the element, but somethings wrong.

<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <meta name="author" content="franverona">
    <meta name="description" content="Javascript plugin for using your own images as a progress bar">
    <meta name="keywords" content="loadgo jquery plugin progress bar javascript html5 web development">

    <title>LoadGo - Your own images as a progress bar</title>

    <link rel="stylesheet" type="text/css" href="bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="style.css">
    <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
	  <script type="text/javascript" src="jquery-1.11.2.min.js"></script>
	  <script type="text/javascript" src="../loadgo.js"></script>


  </head>
  <body>
  <div class="pace  pace-inactive"><div class="pace-progress" style="transform: translate3d(100%, 0px, 0px);" data-progress-text="100%" data-progress="99">
  <div class="pace-progress-inner"></div>
</div>
<div class="pace-activity"></div></div>
<div id="loadgo-logo-overlay" style="display: none;">
    <div id="loadgo-internal" style="width: 700px; height: 487px;">
      <img style="display: block;" alt="logo" src="logos/disney.png" id="loadgo-logo"><div class="loadgo-overlay" style="background-color: rgb(255, 255, 255); opacity: 0.5; width: 0px; height: 487px; left: 700px; top: 0px; position: absolute;"></div>
      <h3 style="display: block; color: rgb(0, 0, 0);" id="loadgo-progress">100%</h3>
      <div style="display: block; color: rgb(0, 0, 0);" id="loadgo-message">Loader provided by LoadGo for WP</div>
    </div>
  </div>
    <script type="text/javascript">
        var LOADGO_LOGO = document.getElementById('loadgo-logo');
    document.getElementsByTagName('body')[0].style.overflow = 'hidden';
    LOADGO_LOGO.onload = function () {
          document.getElementById('loadgo-message').style.display = 'block';
              document.getElementById('loadgo-progress').style.display = 'block';
          var interval = window.setInterval(function () {
        if (typeof Loadgo !== 'undefined') {
          LOADGO_LOGO.style.display = 'block';

          var overlayDOM = document.getElementById('loadgo-internal');

          var perc = 100, 
              width = LOADGO_LOGO.width * (perc / 100), 
             height = LOADGO_LOGO.height * (perc / 100);
          overlayDOM.style.width = width + 'px';
          overlayDOM.style.height = height + 'px';

          var loadgoParams = {
            bgcolor:      '#ffffff',
            opacity:      '0.5',
            direction:    'lr',
            animated:     false
          };
          Loadgo.init(LOADGO_LOGO, loadgoParams);
          window.clearInterval(interval);
        }
      }, 100);

      // Dispatch resize event when LoadGo finish
      var resizeInterval = window.setInterval(function () {
        if (typeof Loadgo !== 'undefined') {
          if (Loadgo.getprogress(LOADGO_LOGO) === 100) {
            window.dispatchEvent(new Event('resize'));
            window.clearInterval(resizeInterval);
          }
        }
      }, 100);
    };
  
</script>
    <div class="container" style="padding-top:60px;padding-bottom:60px;background: #fff;position:relative;">
Here is the body
    </div>

  </body>
   <script type="text/javascript" src="pace.js"></script>


</html>


Thank for your time

**Comment by franverona** [comment]
I can't test your code right now, but one of the problems that I'm seeing is that you are loading the jQuery version of LoadGo, but using the non jQuery version to initialize and set progress.

The jQuery version is different from non jQuery version. Change this line:
`<script type="text/javascript" src="../loadgo.js"></script>`
For this one (be sure that [you have the file](https://github.com/franverona/loadgo/blob/master/loadgo-nojquery.js)):
`<script type="text/javascript" src="../loadgo-nojquery.js"></script>`
And make sure that your Pace script has the right functions inside (like I described previously).

For this particular file you don't need jQuery at all, so you can remove it if you like. In your original case maybe you will need it for other JS code of your own, but LoadGo + Pace solution just needs non jQuery version of LoadGo and Pace (in that particular order).

Let me know it that works :+1: 

-Fran

**Comment by Dankof** [comment]
Ok, just fix this bug, now I get new one with this meesage back

Trying to set progress for a non initialized element. You have to run "init" method first.
...'Trying to set progress for a non initialized element. You have to run "init" me...

Any suggestions? :)

**Comment by franverona** [comment]
I think your problem now could be that Pace is trying to load it before your other scripts (LoadGo too) so LoadGo is never initialized before Pace (even loading LoadGo before Pace like you did).

In my Wordpress plugin I can control this by setting loading priorities, so I can say "hey Pace, wait for LoadGo" (`$deps` parameters in [wp_enqueue_script](https://developer.wordpress.org/reference/functions/wp_enqueue_script/) function). In your case I don't know how to do it. I can only suggest you to take a look at [Pace API documentation](http://github.hubspot.com/pace/) or give a try to other libraries to load your own scripts like [RequireJS](http://requirejs.org/).

-Fran

**Comment by franverona** [comment]
I will close this due to innactivity. Feel free to open another one if you still have the same issue.
